//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdCond
    {
        public int IDProdCond { get; set; }
        public int ID_Product { get; set; }
        public int ID_Condition { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Product Product { get; set; }
    }
}
