//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int IDTransaction { get; set; }
        public int ID_Client { get; set; }
        public int ID_TrTType { get; set; }
        public string Date { get; set; }
        public int ID_Emp { get; set; }
        public int ID_Place { get; set; }
        public int ID_Product { get; set; }
        public double Amount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Place Place { get; set; }
        public virtual Product Product { get; set; }
        public virtual TransType TransType { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
