//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRequest
    {
        public int ID_Request { get; set; }
        public string FullName { get; set; }
        public string requestTime { get; set; }
        public string computerName { get; set; }
        public int requestState { get; set; }
        public int requestTypeID { get; set; }
        public int userID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual reqType reqType { get; set; }
    }
}
